LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE		:= libbullet
LOCAL_CPP_EXTENSION := cpp
LOCAL_CFLAGS		:= -Werror -O2
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_SRC_FILES	:= \
   ./LinearMath/btGeometryUtil.cpp \
   ./LinearMath/btQuickprof.cpp \
   ./LinearMath/btConvexHullComputer.cpp \
   ./LinearMath/btConvexHull.cpp \
   ./LinearMath/btAlignedAllocator.cpp \
   ./LinearMath/btSerializer.cpp \
   ./BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
   ./BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
   ./BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
   ./BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
   ./BulletDynamics/Character/btKinematicCharacterController.cpp \
   ./BulletDynamics/Vehicle/btWheelInfo.cpp \
   ./BulletDynamics/Vehicle/btRaycastVehicle.cpp \
   ./BulletDynamics/Dynamics/Bullet-C-API.cpp \
   ./BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
   ./BulletDynamics/Dynamics/btRigidBody.cpp \
   ./BulletDynamics/Dynamics/btContinuousDynamicsWorld.cpp \
   ./BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
   ./BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
   ./BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
   ./BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
   ./BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
   ./BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
   ./BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
   ./BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
   ./BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
   ./BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
   ./BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
   ./BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
   ./BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
   ./BulletCollision/CollisionDispatch/btUnionFind.cpp \
   ./BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
   ./BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btGhostObject.cpp \
   ./BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
   ./BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
   ./BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
   ./BulletCollision/CollisionDispatch/btCollisionObject.cpp \
   ./BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
   ./BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
   ./BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
   ./BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
   ./BulletCollision/CollisionDispatch/btManifoldResult.cpp \
   ./BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
   ./BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp \
   ./BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
   ./BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
   ./BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
   ./BulletCollision/BroadphaseCollision/btDispatcher.cpp \
   ./BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
   ./BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
   ./BulletCollision/BroadphaseCollision/btDbvt.cpp \
   ./BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
   ./BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
   ./BulletCollision/CollisionShapes/btConcaveShape.cpp \
   ./BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
   ./BulletCollision/CollisionShapes/btSphereShape.cpp \
   ./BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
   ./BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
   ./BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
   ./BulletCollision/CollisionShapes/btCapsuleShape.cpp \
   ./BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
   ./BulletCollision/CollisionShapes/btCompoundShape.cpp \
   ./BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
   ./BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
   ./BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
   ./BulletCollision/CollisionShapes/btShapeHull.cpp \
   ./BulletCollision/CollisionShapes/btEmptyShape.cpp \
   ./BulletCollision/CollisionShapes/btConvexShape.cpp \
   ./BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
   ./BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
   ./BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
   ./BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
   ./BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
   ./BulletCollision/CollisionShapes/btBoxShape.cpp \
   ./BulletCollision/CollisionShapes/btConvexHullShape.cpp \
   ./BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
   ./BulletCollision/CollisionShapes/btCylinderShape.cpp \
   ./BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
   ./BulletCollision/CollisionShapes/btTriangleMesh.cpp \
   ./BulletCollision/CollisionShapes/btBox2dShape.cpp \
   ./BulletCollision/CollisionShapes/btCollisionShape.cpp \
   ./BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
   ./BulletCollision/CollisionShapes/btConvex2dShape.cpp \
   ./BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
   ./BulletCollision/CollisionShapes/btTriangleCallback.cpp \
   ./BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
   ./BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
   ./BulletCollision/CollisionShapes/btConeShape.cpp \
   ./BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
   ./BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
   ./BulletCollision/Gimpact/gim_memory.cpp \
   ./BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
   ./BulletCollision/Gimpact/btGImpactBvh.cpp \
   ./BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
   ./BulletCollision/Gimpact/gim_box_set.cpp \
   ./BulletCollision/Gimpact/btTriangleShapeEx.cpp \
   ./BulletCollision/Gimpact/btGImpactShape.cpp \
   ./BulletCollision/Gimpact/btContactProcessing.cpp \
   ./BulletCollision/Gimpact/gim_tri_collision.cpp \
   ./BulletCollision/Gimpact/gim_contact.cpp
include $(BUILD_STATIC_LIBRARY)
