TARGET  := ./convert_dds
SOURCES := convert_dds.c
OBJECTS := $(SOURCES:.c=.o)

CC      = gcc
CFLAGS  = -O2 -Wall -Werror -I../libbullet -I../librunner
LDFLAGS = -L. -L../librunner
LIBS    = -lrunner -lm -lGL -lpng

all: $(SOURCES) $(TARGET)

clean:
	rm -rf $(OBJECTS) $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(LDFLAGS) $(CFLAGS) -o $@ $(OBJECTS) $(LIBS)

.c.o:
	$(CC) -c $(CFLAGS) $(@:.o=.c)

