/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_org_asqz_runner_Wrapper */

#ifndef _Included_ua_org_asqz_runner_Wrapper
#define _Included_ua_org_asqz_runner_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ua_org_asqz_runner_Wrapper_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_update
  (JNIEnv *, jclass);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    scroll
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_scroll
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
