/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_org_asqz_runner_Wrapper */

#ifndef _Included_ua_org_asqz_runner_Wrapper
#define _Included_ua_org_asqz_runner_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    init
 * Signature: (Landroid/content/res/AssetManager;)I
 */
JNIEXPORT jint JNICALL Java_ua_org_asqz_runner_Wrapper_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    restore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ua_org_asqz_runner_Wrapper_restore
  (JNIEnv *, jclass);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    update
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ua_org_asqz_runner_Wrapper_update
  (JNIEnv *, jclass);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    activated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_activated
  (JNIEnv *, jclass);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    deactivated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_deactivated
  (JNIEnv *, jclass);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    pointer_down
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_pointer_1down
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    pointer_up
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_pointer_1up
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    pointer_move
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_pointer_1move
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    key_down
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_key_1down
  (JNIEnv *, jclass, jint);

/*
 * Class:     ua_org_asqz_runner_Wrapper
 * Method:    key_up
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ua_org_asqz_runner_Wrapper_key_1up
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
